import { Navbar } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Other pages",
  description: "Generated by AC",
};

export default function GeneralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div>
        <span>general Layout</span>
      </div>
      <Navbar />
      {children}
    </>
  );
}
