import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by AC",
  keywords: ["About me", "ac", "info ac"],
};

export default function AboutPage() {
  return (
    <div>
      <h2 className="text-4xl">about</h2>
    </div>
  );
}
