import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by AC",
};

export default function PricingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <span>Layout only for princing</span>
        </div>
        {children}
      </body>
    </html>
  );
}
